-- Respaldo de usuarios - 2025-06-21_13-25-46
-- Total usuarios: 264

INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('1', 'Administrador', '', '000', 'admin123', 'admin', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('8', 'Alma Sofia', 'ACOSTA ANAYA', '2087', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('9', 'Sebastian', 'ALTOMARE', '2054', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('10', 'Lola', 'ALMARAZ IGLESIAS', '2021', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('11', 'Josias Julian', 'BONIFACIO CAPURRO', '1985', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('12', 'Mateo', 'ALVAREZ', '1946', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('13', 'Ivan Alejandro', 'ALBEROTANZA', '1874', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('14', 'Federico', 'ALBO', '1875', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('15', 'Renzo', 'ALITTA', '2088', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('16', 'Estanislao Felipe', 'BALLESTER', '2055', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('17', 'Felix', 'ANTONIO', '2022', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('18', 'Ramiro', 'BORELLI', '1986', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('19', 'Lucas Emanuel', 'ARTOLA', '1911', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('20', 'Santiago', 'ARIAS ZAMORA', '1910', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('21', 'Mateo', 'BUTLER', '1876', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('22', 'Benjamin', 'ALONSO HESSEL', '2089', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('23', 'Santiago', 'BESSONE', '2056', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('24', 'Joaquin Ezequiel', 'BOGAO', '2023', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('25', 'Tomas', 'CELESTINO', '1987', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('26', 'Juan Cruz', 'BARROS', '1947', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('27', 'Luciana Corina', 'CABAÑA', '1912', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('28', 'Benicio Benjamin', 'CALVO SCHMIDT', '1878', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('29', 'Maximo', 'BARROS', '2090', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('30', 'Mateo Joaquin', 'BOGADO', '2057', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('31', 'Gregorio', 'BRIZIO TRÍAS', '2024', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('32', 'Fabrizio Adrian', 'CHIODO', '1988', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('33', 'Facundo Elias', 'BOHORQUEZ', '1948', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('34', 'Tomas Ariel', 'CAMPERO', '1914', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('35', 'Agustin', 'CORNELL', '1880', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('36', 'Benjamin Daniel', 'BECERRA', '2091', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('37', 'Joaquin', 'CABRAL LANGE', '2058', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('38', 'Marcelo Alejandro', 'CACERES GARCIA', '2025', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('39', 'Tomas', 'COLONNA', '1989', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('40', 'Matias Angel', 'CAPINO LEICHNER', '1949', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('41', 'Luis Javier', 'CARDOZO', '1915', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('42', 'Valentino', 'CORRAL', '1881', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('43', 'Abigail Coral', 'BONIFACIO CAPURRO', '2092', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('44', 'Donato Thadeo', 'CELESTINO', '2059', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('45', 'Mauro Valentino', 'CALABRO', '2026', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('46', 'Benjamin Alan', 'CROCCO', '1990', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('47', 'Luciano', 'COSTA', '1950', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('48', 'Mateo Cesar', 'CASSANO', '1916', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('49', 'Maximo', 'D´NARDO', '1882', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('50', 'Francisco', 'BUCETA CASTILLA SASTRE', '2093', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('51', 'Carlos Nahuel', 'CORREA', '2060', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('52', 'Bruno Nicolas', 'CARABAJAL', '2027', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('53', 'Nicolás Agustín', 'DAPPIANO', '1991', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('54', 'Genaro', 'DERBALIAN', '1951', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('55', 'Diego Franco', 'CELESTINO', '1917', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('56', 'Juan Bautista', 'DUFOUR', '1883', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('57', 'Bautista', 'CABRERA', '2094', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('58', 'Juan Ignacio', 'CURCIO', '2061', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('59', 'Catalina', 'DI FIORE', '2028', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('60', 'Alejo Gael', 'DEZULOVICH FURNUS', '1992', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('61', 'Luca', 'DIFINO', '1952', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('62', 'Ignacio Dante', 'DIAZ', '1919', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('63', 'Juan Lucas', 'ECHEVERRIA', '1884', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('64', 'Maximo Rafael', 'DEL CASTILLO', '2095', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('65', 'Francisco', 'DIORIO GANCEDO', '2062', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('66', 'Alan Ivan', 'DIAZ', '2029', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('67', 'Alejandro', 'DOMINGUEZ SERROT', '1993', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('68', 'Juan Cruz', 'FERNANDEZ ERUT', '1954', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('69', 'Santiago Alejandro', 'DI CIOCCO', '1920', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('70', 'Bruno', 'FERRARI BARTOSZYK', '1846', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('71', 'Agustin Paul', 'DIAZ', '2096', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('72', 'Guillermo Ezequiel', 'DORSCH', '2063', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('73', 'Simon', 'DONDO CIFUENTES', '2030', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('74', 'Agustín', 'FRANGOLINI', '1994', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('75', 'Tiziano', 'FICHERA', '1982', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('76', 'Felix Ezequiel', 'FANGIO', '1921', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('77', 'Federico Benjamin', 'FRETEZ', '1885', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('78', 'Joaquin Emiliano', 'ELLACOPULOS', '2097', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('79', 'Benicio', 'DURST NONELL', '2064', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('80', 'Santiago Jose', 'ESTEYBAR MOLLO', '2031', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('81', 'Ian Adriel', 'GOMEZ FRIEDL', '1996', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('82', 'Mateo', 'GIMENEZ', '1955', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('83', 'Joaquin Tiziano', 'FLORES', '1922', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('84', 'Pedro', 'GARBARINO', '1886', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('85', 'Bastian Lorenzo', 'FERNANDEZ', '2098', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('86', 'Viggo Roman', 'FERNANDEZ', '2065', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('87', 'Thiago Nicolas', 'FERNANDEZ', '2032', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('88', 'Anna Martina', 'GUILLERMO', '1997', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('89', 'Bautista', 'GOTTI', '1927', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('90', 'Agustín', 'FORTUNATTI BASTIANELI', '1923', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('91', 'Lucio Manuel', 'GOLSBERG', '1887', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('92', 'Jeremias Bastian', 'GALLARDO COPPES', '2099', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('93', 'Rodrigo Nicolas', 'GOMEZ ETCHART', '2066', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('94', 'Juan Lautaro', 'FERRARI', '2033', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('95', 'Juan Werner', 'HENTSCHEL', '1998', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('96', 'Zadkiel David', 'JIMENEZ ESPINOZA', '1957', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('97', 'Nicolás', 'FRANGOLINI', '1924', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('98', 'Felipe', 'HOURIE ARESO', '1889', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('99', 'Juan Martin', 'GIL BERETERBIDE', '2100', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('100', 'Lucia', 'LANFRANCO SERVIN', '2067', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('101', 'Agustin Ezequiel', 'FERREYRA', '2034', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('102', 'Tiago', 'INGUANZO TRILLO', '1999', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('103', 'Emma Catalina', 'LUTY GUILLERMO', '1958', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('104', 'Matias', 'GARCIA CASAL', '1925', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('105', 'Nicolas Maximo', 'KIRICZKO', '1891', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('106', 'Romeo', 'GIUBBILINI', '2101', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('107', 'Ignacio Ezequiel', 'LEVERATTO STASTNY', '2068', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('108', 'Thiago Benjamin', 'GAITTO BELTRAMI', '2035', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('109', 'Francisco Ramiro', 'JEREZ', '2000', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('110', 'Lucas Gabriel', 'MAGALLAN', '1932', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('111', 'Mateo', 'GIUBBILINI', '1926', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('112', 'Juan Francisco', 'LAMOLINA', '1892', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('113', 'Juan Pablo', 'GOMEZ GARCETE', '2102', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('114', 'Benicio Valentin', 'LOPEZ', '2069', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('115', 'Felipe', 'GALLI DA FONSECA', '2036', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('116', 'Matias', 'LAFON MIRI', '2001', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('117', 'Andres', 'MAJEWSKI', '1959', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('118', 'Santiago', 'ICONOMOPULOS', '1928', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('119', 'Alma Agustina', 'MALATESTA', '1893', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('120', 'Jonas Bautista', 'HORNOS', '2103', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('121', 'Natalia Soledad', 'MATEO BAUTISTA', '2070', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('122', 'Benicio', 'GIUBBILINI', '2037', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('123', 'Facundo', 'LO CARMINE', '2002', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('124', 'Joaquin', 'MAJEWSKI', '1960', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('125', 'Ramiro Valentín', 'IGLESIAS', '1929', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('126', 'Franco Jose', 'MARIANI', '1894', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('127', 'Ramiro', 'INGUANZO TRILLO', '2104', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('128', 'Joaquin Thomas', 'MINARDI', '2071', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('129', 'Kiara Guadalupe', 'GONZALEZ UÑATE', '2038', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('130', 'Franco Nicolás', 'NAYA', '2003', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('131', 'Santiago Daniel', 'MARAI', '1961', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('132', 'Santino', 'LANFRANCO SERVIN', '1930', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('133', 'Maximo', 'MARZULLO ALANIZ', '1895', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('134', 'Bautista Uriel', 'LARROSA', '2105', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('135', 'Santiago', 'MORANDI', '2072', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('136', 'Tobias Benjamin', 'GRIMALDI', '2039', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('137', 'Federico', 'PERIN', '2004', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('138', 'Andrés', 'MARCHETTI', '1934', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('139', 'Mateo', 'LENCE', '1931', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('140', 'Victoria Mercedes', 'MATEO BAUTISTA', '1896', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('141', 'Franco', 'LENCE', '2106', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('142', 'Simon', 'MOSQUERA', '2073', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('143', 'Martina Abril', 'KINEN', '2040', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('144', 'Nicolás ', 'PERIN', '2005', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('145', 'Juan Sebastian', 'MONTENOVI', '1964', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('146', 'Federico Nicolás', 'MANSILLA', '1933', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('147', 'Pedro Leon', 'OROÑO', '1897', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('148', 'Nicolas', 'MISLEJ', '2107', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('149', 'Juan Francisco', 'NISELLI', '2074', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('150', 'Maximo Valentino M.', 'MAIDANA MARENGO', '2041', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('151', 'Santino', 'PERROTTA', '2006', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('152', 'Tomas', 'MORENO MARTINEZ', '1962', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('153', 'Juan Martín', 'MUSOLINO', '1935', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('154', 'Mariano Gabriel', 'PEREIRA', '1898', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('155', 'Fernando Valentino', 'MONTENOVI', '2108', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('156', 'Francisco Dario', 'PUERTAS', '2075', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('157', 'Ezequiel', 'NAHÚM', '2042', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('158', 'Felipe', 'PEYDRO', '2007', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('159', 'Libertad Sofia', 'NANDIN', '1965', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('160', 'Maria Agustina', 'NEMI', '1936', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('161', 'Imanol Cruz', 'RODRIGUEZ', '1900', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('162', 'Gonzalo Angel', 'MOYANO', '2109', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('163', 'Julian Bautista', 'RODRIGUEZ', '2076', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('164', 'Julieta', 'NUÑEZ ZAYAS', '2043', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('165', 'Alejandro Martín', 'PRAVATO', '2008', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('166', 'Ignacio', 'PIREZ GOSENDE', '1966', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('167', 'Santiago', 'PEREZ DEL VALLE', '1937', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('168', 'Tomas Alejandro', 'RODRIGUEZ', '1901', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('169', 'Jose Francisco', 'MUIÑOS', '2110', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('170', 'Juan Ignacio', 'RODRIGUEZ GRAFFIGNA', '2077', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('171', 'Valentin Emmanuel', 'PRIETO', '2044', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('172', 'Maia Guadalupe', 'PUMAREGA', '2009', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('173', 'Bautista Nahuel', 'PRESENTADO', '1968', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('174', 'Matias Andres', 'PEREZ ROSSI', '1938', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('175', 'Ramiro', 'SANTELLAN', '1904', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('176', 'Erik Ezequiel', 'NAVNTOFT', '2111', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('177', 'Lautaro Lionel', 'RUFFOLO', '2078', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('178', 'Francisco', 'PUGLISI', '2045', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('179', 'Lucio Lias', 'QUINTELA SANDOVAL', '1983', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('180', 'Julian Martin', 'PRETZEL', '1969', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('181', 'Ezequiel', 'ROMAGNOLI TISCORNIA', '1939', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('182', 'Iago', 'TANGORRA KINDSVATER', '1905', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('183', 'Felipe', 'PEREYRA PIBERNAT', '2112', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('184', 'Martin Lautaro', 'RUPANI', '2079', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('185', 'Manuel', 'RIVA', '2046', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('186', 'Joaquin Bautista Ariel', 'RAMIREZ', '2019', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('187', 'Lautaro', 'RABANOS LENI', '1970', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('188', 'Sofia Rocio', 'ROMERA', '1940', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('189', 'Tiziano', 'TRAMONTOZZI PORTO', '1906', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('190', 'Luciano', 'PITASHNY DEL POPOLO', '2113', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('191', 'Marino Francesco', 'SASSO MÉROLA', '2080', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('192', 'Felipe', 'SAENZ BRIONES', '2047', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('193', 'Ignacio Agustín', 'RELA', '2010', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('194', 'Agustin', 'RIVA', '1972', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('195', 'Facundo Juan', 'RUANO', '1941', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('196', 'German Andres', 'TREMBINSKY', '1907', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('197', 'Agustin Matias', 'PRAVATO', '2114', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('198', 'Santiago', 'SCRIGNA', '2081', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('199', 'Santino Nicolas', 'TCHERECHANSKY', '2048', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('200', 'Juan Marcos', 'RODRIGUEZ', '2011', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('201', 'Mateo Ignacio', 'ROSSO', '1974', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('202', 'Eliseo Martín', 'SERVIAN', '1942', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('203', 'Lourdes', 'TURRI', '1873', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('204', 'Federico Ivan', 'RIVAS', '2115', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('205', 'Facundo Santiago', 'TELLARINI', '2082', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('206', 'Matias', 'TORRES AGRELO', '2049', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('207', 'Augusto', 'SALVIA', '2014', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('208', 'Ignacio', 'SCHENONE', '1975', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('209', 'Santiago Benjamín', 'SILVA', '1943', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('210', 'Alexander Daniel', 'SANCHEZ', '2116', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('211', 'Juan Pablo', 'TURNER', '2083', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('212', 'Micaela', 'VAGNI AGUIRRE', '2050', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('213', 'Ezequiel Ivan', 'SCHULTHEIS', '2015', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('214', 'Lucas', 'SECADES', '1976', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('215', 'Agustín Nicolás', 'TCHERECHANSKY', '1944', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('216', 'Selene Abigail', 'SANCHEZ', '2117', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('217', 'Ivan Augusto', 'VERON', '2084', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('218', 'Mariano', 'VENTOSO', '2051', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('219', 'Juan Ignacio', 'TORRES', '2016', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('220', 'Lorenzo Tomas', 'SORIA', '1978', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('221', 'Franco Giovanni', 'TERENZIO', '1945', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('222', 'Katya Sara', 'SEILHAN', '2118', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('223', 'Alma Macarena', 'VILLANEDA', '2085', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('224', 'Luca', 'VENTURELLI', '2052', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('225', 'Joaquin', 'VUELTA LANNUTTI', '2017', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('226', 'Federico', 'SORIA CAMPAGNONI', '1979', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('227', 'Emmanuel Alejandro', 'SKAMARDA', '2119', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('228', 'Joaquin', 'ZARZA LAFUENTE', '2086', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('229', 'Santiago Augusto', 'VERGARA', '2053', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('230', 'Agustín Ignacio', 'ZAMBRANO WEISS', '2018', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('231', 'Liam', 'VAN RIJSWIJK', '2120', 'estudiante123', 'estudiante', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('271', 'Marta', 'CID DE LOPEZ', '00000001', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('272', 'Federico', 'IGLESIAS', '00000003', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('273', 'Cecilia', 'MARISTANY', '00000005', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('274', 'Alejandro', 'GENDRA', '00000007', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('275', 'Daniel', 'DOTTORI', '00000009', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('276', 'Paula', 'FERRARI', '00000011', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('277', 'Martín', 'CHACÓN', '00000013', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('278', 'María Victoria', 'GÓMEZ', '00000015', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('279', 'Federico', 'GALDEANO', '00000017', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('280', 'Brian', 'CARDALDA', '00000019', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('281', 'Edgardo', 'KLOSTER', '00000021', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('282', 'Jorge', 'BELMONTE', '00000023', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('283', 'Diego', 'MONTOTO', '00000025', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('284', 'Dante', 'PRESENTADO', '00000028', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('285', 'Pablo', 'LANFRANCO', '00000030', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('286', 'Carlos', 'ROMANO', '00000033', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('287', 'Juan Martín', 'KIAHIAYAN', '00000037', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('288', 'Sergio', 'BANGERT', '00000039', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('289', 'Rosana', 'BÁLSAMO', '00000042', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('290', 'Alejandro', 'MANNIELLO', '00000044', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('291', 'Marina', 'CATALANO', '00000053', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('292', 'Gonzalo', 'CASTRO', '00000054', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('293', 'Gerardo', 'RICCHINI', '00000057', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('294', 'Candela', 'SÁNCHEZ', '00000060', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('295', 'Daniel', 'OJEDA', '00000063', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('296', 'Marcela', 'PAZ', '00000069', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('297', 'Francisco', 'FERNÁNDEZ', '00000085', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('298', 'Daniel', 'BARRIO', '00000089', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('299', 'Marcelo', 'DARGET', '00000091', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('300', 'Javier', 'MELLINO', '00000098', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('301', 'Gabriel', 'ARIAS', '00000100', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('302', 'Ezequiel', 'LAGO', '00000103', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('303', 'Marcelo', 'NETO', '00000118', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('304', 'Maximiliano', 'PIZZOLATO', '00000127', 'profesor123', 'profesor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('305', 'Natalia', 'MANTUANI', '11222333', 'preceptor123', 'preceptor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('306', 'Juan', 'BENTANCOR', '11222444', 'preceptor123', 'preceptor', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('307', 'Susana', 'AMBROSONI', '99888777', 'directivo123', 'directivo', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('308', 'Jorge', 'LAGO', '99888666', 'directivo123', 'directivo', '1', '0');
INSERT INTO usuarios_respaldo (id, nombre, apellido, dni, contrasena, tipo, activo, password_changed) VALUES ('309', 'Carlos', 'MIÑO', '11222555', 'preceptor123', 'preceptor', '1', '0');
